#!/usr/bin/env python3
"""Korean translation coverage report.

Scans every scene for dialogue-like string literals and cross-references the
Korean dictionary (src/data/ko_strings.ts) to show, per scene, how many lines
are translated vs. remaining. Run from phaser-game/:  python3 scripts/translation_coverage.py
Writes docs/translation_coverage.md and prints a summary.
"""
import re, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

# ── Load the Korean dictionary (keys of KO_STRINGS + KO_SPEAKERS) ──
ko = open('src/data/ko_strings.ts', encoding='utf-8').read()
def keys_of(block: str):
    # keys are the quoted string before ':' at the start of a dict entry
    return set(re.findall(r"^\s*'((?:[^'\\]|\\.)*)'\s*:", block, re.M))
KO_STRINGS = keys_of(ko)
KO_SPEAKERS = set()
m = re.search(r"KO_SPEAKERS[^{]*\{(.*?)\n\};", ko, re.S)
if m: KO_SPEAKERS = keys_of(m.group(1))

def unesc(s): return s.replace("\\'", "'").replace('\\n', '\n')

# ── Candidate dialogue literal: quoted, has a space + lowercase letter, decent
# length, and not obviously code/asset/style. Skips template literals (no scan of `...`).
LIT = re.compile(r"'((?:[^'\\]|\\.){12,300})'")
BAD = re.compile(r"assets/|https?:|#[0-9a-fA-F]{3,}\b|fontSize|backgroundColor|\.png|\.mp3|addKey|Scene'$|\bimport\b|font(Style|Family)|strokeThickness")

def covered(line: str) -> bool:
    if line in KO_STRINGS: return True
    i = line.find(': ')
    if 0 < i <= 24:
        return (line[:i] in KO_SPEAKERS) and (line[i+2:] in KO_STRINGS)
    return False

rows = []
tot_lines = tot_cov = 0
for path in sorted(glob.glob('src/scenes/**/*.ts', recursive=True)):
    txt = open(path, encoding='utf-8').read()
    seen, n, c = set(), 0, 0
    for mm in LIT.finditer(txt):
        v = unesc(mm.group(1))
        if BAD.search(v): continue
        if ' ' not in v or not re.search(r'[a-z]', v): continue
        if v in seen: continue
        seen.add(v); n += 1
        if covered(v): c += 1
    if n == 0: continue
    rows.append((os.path.basename(path)[:-3], n, c, n - c))
    tot_lines += n; tot_cov += c

rows.sort(key=lambda r: -r[3])
pct = (100 * tot_cov / tot_lines) if tot_lines else 0
os.makedirs('docs', exist_ok=True)
with open('docs/translation_coverage.md', 'w', encoding='utf-8') as f:
    f.write('# Korean Translation Coverage\n\n')
    f.write(f'Auto-generated by `scripts/translation_coverage.py`.\n\n')
    f.write(f'**Overall: {tot_cov} / {tot_lines} candidate lines translated ({pct:.1f}%).**\n\n')
    f.write('_"Candidate lines" = static (non-template) dialogue-like literals; templated '
            '`${...}` lines and pure UI aren\'t counted here._\n\n')
    f.write('| Scene | Translated | Remaining | Total |\n|---|--:|--:|--:|\n')
    for name, n, c, rem in rows:
        f.write(f'| {name} | {c} | {rem} | {n} |\n')

print(f'Overall: {tot_cov}/{tot_lines} lines ({pct:.1f}%) across {len(rows)} scenes')
print('Top 15 scenes by remaining lines:')
for name, n, c, rem in rows[:15]:
    print(f'  {rem:4d} remaining  ({c}/{n})  {name}')
print('\nReport written to docs/translation_coverage.md')
